dist: trusty
sudo: false

language: c

matrix:
  include:
    - env: CABALVER="1.24" GHCVER="8.0.2"
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
  - cabal sandbox init
  - cabal install Cabal
  - make

script:
  - make test

notifications:
  email: false
