dist: trusty
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    - env: CABALVER="2.4" GHCVER="8.4.4" GHCSHORTVER="84"
      compiler: ": #GHC 8.4.4"
      addons: {apt: {packages: [cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
    - env: CABALVER="3.0" GHCVER="8.6.5" GHCSHORTVER="86"
      compiler: ": #GHC 8.6.5"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.6.5], sources: [hvr-ghc]}}
    - env: CABALVER="3.0" GHCVER="8.8.1" GHCSHORTVER="88"
      compiler: ": #GHC 8.8.1"
      addons: {apt: {packages: [cabal-install-3.0,ghc-8.8.1], sources: [hvr-ghc]}}

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]];
    then
        mkdir -p $HOME/bin;
        export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/bin:$HOME/.cabal/bin:$PATH;
        curl https://saw.galois.com/builds/z3/z3 > z3;
        chmod +x z3;
        mv z3 $HOME/bin/z3;
        z3 --version;
    fi
  - env

script:
  - cp cabal.GHC${GHCSHORTVER}.config cabal.project.freeze
  - cabal update
  - bash cry build
  - bash cry test

notifications:
  email: false
