dist: trusty
sudo: false

language: c

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

matrix:
  include:
    - env: CABALVER="2.0" GHCVER="8.2.1"
      compiler: ": #GHC 8.2.1"
      addons: {apt: {packages: [cabal-install-2.0,ghc-8.2.1], sources: [hvr-ghc]}}
    - os: osx
      env: CABALVER="2.0" GHCVER="8.2.1"
      compiler: ": #GHC 8.2.1"

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]];
    then
        mkdir -p $HOME/bin;
        export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/bin:$HOME/.cabal/bin:$PATH;
        curl https://saw.galois.com/builds/z3/z3 > z3;
        chmod +x z3;
        mv z3 $HOME/bin/z3;
        z3 --version;
    fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]];
    then
        brew install ghc cabal-install z3;
        export PATH=$HOME/.cabal/bin:$PATH;
    fi
  - env

script:
  - cabal update
  - cabal new-build -j

notifications:
  email: false
