name: Cryptol Dockerfile
on:
  push:
    branches:
      - "actions/*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Cryptol Docker
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: outputs
        run: .github/ci.sh output version cryptol-$(.github/ci.sh ver)-$(date -I)

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: galoisinc/cryptol
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ steps.outputs.outputs.version }}"
