name: Docker
on:
  push:
    tags: ["v?[0-9]+.[0-9]+(.[0-9]+)?"]
  workflow_dispatch:
    inputs:
      image-to-build:
        description: "Manually build and push a docker image (cryptol|cryptol-remote-api)"
        required: false
        default: ""

jobs:
  cryptol:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' || github.event.inputs.image-to-build == 'cryptol'"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: .github/ci.sh set_version
        id: outputs
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GITHUBCRYPTOL_USERNAME }}
          password: ${{ secrets.GITHUBCRYPTOL }}
          repository: galoisinc/cryptol
          tags: "latest,${{ steps.outputs.outputs.cryptol-version }}"
          add_git_labels: true
          push: true
  cryptol-remote-api:
    if: "github.event_name == 'push' || github.event.inputs.image-to-build == 'cryptol-remote-api'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: .github/ci.sh set_version
        id: outputs
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GITHUBCRYPTOL_USERNAME }}
          password: ${{ secrets.GITHUBCRYPTOL }}
          repository: galoisinc/cryptol-remote-api
          tags: "latest,${{ steps.outputs.outputs.cryptol-version }}"
          add_git_labels: true
          build_args: GHCVER=8.10.3
          push: true
          dockerfile: cryptol-remote-api/Dockerfile
