name: Docker
on:
  workflow_dispatch:
  push:
    tags: ["v?[0-9]+.[0-9]+.[0-9]+"]

jobs:
  cryptol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: .github/ci.sh set_version
        id: outputs
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GITHUBCRYPTOL_USERNAME }}
          password: ${{ secrets.GITHUBCRYPTOL }}
          repository: galoisinc/cryptol
          tags: "latest,${{ steps.outputs.outputs.cryptol-version }}"
          add_git_labels: true
          push: true
  cryptol-remote-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: .github/ci.sh set_version
        id: outputs
      - name: Publish to Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.GITHUBCRYPTOL_USERNAME }}
          password: ${{ secrets.GITHUBCRYPTOL }}
          repository: galoisinc/cryptol-remote-api
          tags: "latest,${{ steps.outputs.outputs.cryptol-version }}"
          add_git_labels: true
          push: true
          dockerfile: .github/Dockerfile-remote-api
